# Generated by Django 4.2.4 on 2023-09-04 17:06

import backend.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='Логин')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Эл. почта')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активирован')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Персонал')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Номер телефона')),
                ('first_name', models.CharField(max_length=16, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=16, null=True, verbose_name='Фамилия')),
                ('age', models.IntegerField(null=True, verbose_name='Возраст')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Мужчина'), ('W', 'Женщина')], max_length=1, verbose_name='Пол')),
                ('city', models.CharField(blank=True, max_length=32, verbose_name='Город')),
                ('description_user', models.CharField(blank=True, max_length=512, verbose_name='О себе')),
                ('subscription', models.CharField(default='FREE', max_length=16, verbose_name='Тип подписки')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'unique_together': {('email',)},
            },
            managers=[
                ('objects', backend.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Наименование товара')),
                ('shop', models.CharField(blank=True, max_length=32, verbose_name='Интернет-магазин')),
                ('description', models.CharField(blank=True, max_length=512, verbose_name='Описание товара')),
                ('old_price', models.IntegerField(null=True, verbose_name='Цена до скидки')),
                ('current_price', models.IntegerField(verbose_name='Цена со скидкой')),
                ('url', models.URLField(db_index=True, unique=True, verbose_name='URL товара')),
                ('image', models.URLField(blank=True, verbose_name='URL изображения')),
                ('category', models.CharField(blank=True, max_length=32, verbose_name='Категория')),
                ('brand', models.CharField(blank=True, max_length=32, verbose_name='Бренд')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Ссылка для отслеживания')),
                ('price', models.IntegerField(null=True, verbose_name='Желаемая цена')),
                ('discount', models.IntegerField(null=True, verbose_name='Желаемая скидка')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания запроса')),
                ('complited_at', models.DateField(default=None, null=True, verbose_name='Дата завершения запроса')),
                ('period_date', models.DateField(null=True, verbose_name='Время отслеживания')),
                ('status', models.CharField(default='В работе', max_length=8, verbose_name='Статус запроса')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='backend.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
